version: "3"

services:
    api:
        build:
            context: .
            dockerfile: api.dockerfile
            args:
                - APP_PORT
        restart: always
        environment:
            - NODE_ENV=development
            - TYPEORM_HOST=postgres
        ports:
            - "127.0.0.1:${APP_PORT}:${APP_PORT}"
        env_file:
            - .env
        volumes:
            - .:/usr/src/app
        command: sh -c "yarn install && yarn start db.migrate && yarn start serve"
        networks:
            - backend

    postgres:
        build:
            context: .
            dockerfile: postgres.dockerfile
            args:
                - TYPEORM_PORT
        restart: always
        environment:
            - POSTGRES_USER=${TYPEORM_USERNAME}
            - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
            - POSTGRES_DB=${TYPEORM_DATABASE}
        ports:
            - "127.0.0.1:${TYPEORM_PORT}:${TYPEORM_PORT}"
        volumes:
            - pgdata:/var/lib/postgresql/data:rw
        networks:
            - backend

volumes:
    pgdata:

networks:
    # The API service will be on the backend network
    backend:
        driver: bridge
